apiVersion: v1
kind: Service
metadata:
  name: { { .Values.appName } }
  namespace: { { .Values.appName } }
  labels:
    app.kubernetes.io/instance: { { .Values.appName } }
    app.kubernetes.io/name: { { .Values.appName } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { .Values.appName } }
  ports:
    - port: { { .Values.service.serverPort } }
      targetPort: { { .Values.service.serverPort } }
