prometheus:
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
  port: 9090
  path: /

rules:
  # default: true
  # custom: []
  external:
  - seriesQuery: '{__name__="heavywork_requests_total",job="python-app",namespace!="",pod!=""}'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  annotations: {}
  port: 443
  type: ClusterIP

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: prometheus

rbac:
  create: true

pspEnabled: false

nodeSelector: {}
tolerations: []
affinity: {}
